// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3mzyjpXTIXUr6ZfkdZOJayObb6OrOrmU',
    appId: '1:611155495755:web:51b052dc5b30801ac6b6ce',
    messagingSenderId: '611155495755',
    projectId: 'ziltime-7992c',
    authDomain: 'ziltime-7992c.firebaseapp.com',
    storageBucket: 'ziltime-7992c.firebasestorage.app',
    measurementId: 'G-Y3VWQT3JME',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3mzyjpXTIXUr6ZfkdZOJayObb6OrOrmU',
    appId: '1:611155495755:web:2aa5841e8f6b3d7fc6b6ce',
    messagingSenderId: '611155495755',
    projectId: 'ziltime-7992c',
    authDomain: 'ziltime-7992c.firebaseapp.com',
    storageBucket: 'ziltime-7992c.firebasestorage.app',
    measurementId: 'G-1SN9LX8VY3',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB6mcOxh1zEDF3BJDF1uB2mX9itx_vKMwQ',
    appId: '1:611155495755:ios:cad50a983aa50b67c6b6ce',
    messagingSenderId: '611155495755',
    projectId: 'ziltime-7992c',
    storageBucket: 'ziltime-7992c.firebasestorage.app',
    iosBundleId: 'com.zilmoney.ziltime',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB6mcOxh1zEDF3BJDF1uB2mX9itx_vKMwQ',
    appId: '1:611155495755:ios:cad50a983aa50b67c6b6ce',
    messagingSenderId: '611155495755',
    projectId: 'ziltime-7992c',
    storageBucket: 'ziltime-7992c.firebasestorage.app',
    iosBundleId: 'com.zilmoney.ziltime',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_1StkLiLnUqlC7yAbB2VbyhfZ9pQSGUI',
    appId: '1:611155495755:android:cfcf26574f73eaa9c6b6ce',
    messagingSenderId: '611155495755',
    projectId: 'ziltime-7992c',
    storageBucket: 'ziltime-7992c.firebasestorage.app',
  );
}
